public class T_Player
{
    public string f_id;
    public string f_name;
    public int f_level;
    public string f_icon;
    public int f_exp;
    public string f_model;
    public int f_profession;
    public int f_turn_speed;
    public int f_atk_speed;
    public int f_move_speed;
    public int f_move_standard;
    public int f_mp;
    public int f_magic_speed;
    public int f_magic_atk;
    public int f_atk;
    public int f_defense;
    public int f_hp;
    public int f_hp_speed;
    public int f_hp_atk;
    public int f_hit;
    public int f_dodge;
    public int f_crit;
    public int f_crit_re;
    public int f_crit_damage;
    public int f_crit_re_damage;
    public int f_block;
    public int f_down_time;
    public int f_buff_h;
    public string f_action_sound;
    public string f_action_effect;
    public int f_actor_pabody_condition;
    public string f_skill;
    public string f_passiveskill;
}